### PR TITLE
Updated charter

### PR DESCRIPTION
**Pull request by schiltz3**
Filled out each section with my name above it to make resolving merge conflicts easier
Did not spell check it :(

### CODE REVIEW

**Comment by lilylevrault** [comment]
What does "CI with auto-formatting" mean?

**Comment by schiltz3** [comment]
> What does "CI with auto-formatting" mean?

Continuous integration (CI) is basically automated tests and formatting. So every time you push to a branch or open a PR, GitHub will run the tests, make sure they pass, and format your code.

**Review by TouKoua — COMMENTED** [review]
Maybe add what you expect from meetings? like how long meetings should be or what group members should have done before we meet?

**Comment by schiltz3** [comment]
> Maybe add what you expect from meetings? like how long meetings should be or what group members should have done before we meet?



> Maybe add what you expect from meetings? like how long meetings should be or what group members should have done before we meet?

Updated meeting length and general expectations

**Pull request merged**
